# Generated by Django 4.0.4 on 2022-04-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perforation_register', '0001_initial'),
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='idMuestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perforation_register.registrodeperforacion'),
        ),
    ]
