# Generated by Django 4.0.4 on 2022-04-26 22:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='home1',
            fields=[
                ('nombreProyecto', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('ciudadProyecto', models.CharField(max_length=40)),
                ('fecha', models.DateField(max_length=40)),
                ('ingenieroEncargado', models.CharField(max_length=40)),
                ('cantidad', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('idmembresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suscriptions.membresia')),
            ],
        ),
    ]
