# Generated by Django 4.0.4 on 2022-04-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='correlaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprensibilidad', models.CharField(max_length=30)),
                ('resistenciaCorte', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('cantidadMuestras', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=40)),
                ('firmas', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='parametroSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compresibilidad', models.CharField(max_length=30)),
                ('resistencia', models.CharField(max_length=30)),
                ('elasticidad', models.CharField(max_length=30)),
                ('porcentajeExpansion', models.CharField(max_length=50)),
                ('promedioExpansion', models.CharField(max_length=40)),
                ('pesoEspecificosolido', models.CharField(max_length=50)),
                ('pesoEspecificoagua', models.CharField(max_length=50)),
                ('resistenciaDrenada', models.CharField(max_length=50)),
                ('resistencianoDrenada', models.CharField(max_length=40)),
                ('gravedadEspecifica', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='perfilGeotecnico',
            fields=[
                ('idEstrato', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('espesorEstrato', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Espesor')),
                ('relacionPoisson', models.DecimalField(decimal_places=3, max_digits=10)),
                ('indiceDeComprension', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cc')),
                ('pesoEspecifico', models.DecimalField(decimal_places=3, max_digits=10)),
                ('moduloElasticidad', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Es')),
                ('relacionDeVacioInicial', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='e0')),
                ('presionDepreconsolidacion', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Pc')),
                ('indiceDeExpansibilidad', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cs')),
                ('cohesionSuelo', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cohesion')),
                ('friccionSuelo', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Friccion')),
            ],
        ),
    ]
