# Generated by Django 4.0.4 on 2022-04-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geotechnical_profile', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilgeotecnico',
            name='idproyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1'),
        ),
        migrations.AddField(
            model_name='parametrosuelo',
            name='idproyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1'),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='idproyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1'),
        ),
        migrations.AddField(
            model_name='correlaciones',
            name='idproyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1'),
        ),
    ]
