# Generated by Django 4.0.4 on 2022-04-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registroDePerforacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMuestra', models.CharField(max_length=30)),
                ('profundidadInicial', models.CharField(max_length=20)),
                ('profundidadFinal', models.CharField(max_length=20)),
                ('spt6', models.CharField(max_length=4)),
                ('spt12', models.CharField(max_length=5)),
                ('spt18', models.CharField(max_length=10)),
                ('tipoMuestra', models.CharField(max_length=23)),
                ('clasificacionesPrimarias', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sondeo',
            fields=[
                ('idSondeos', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('coordenadas', models.CharField(max_length=100)),
                ('horaInicial', models.CharField(max_length=30)),
                ('horafinal', models.CharField(max_length=40)),
                ('absisa', models.CharField(max_length=40)),
            ],
        ),
    ]
