# Generated by Django 4.0.4 on 2022-04-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perforation_register', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondeo',
            name='idproyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1'),
        ),
        migrations.AddField(
            model_name='registrodeperforacion',
            name='idSondeos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perforation_register.sondeo'),
        ),
    ]
