# Generated by Django 4.0.4 on 2022-04-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='relacionCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbl', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Relación entre B y L')),
                ('carga', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Carga F3')),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1')),
            ],
        ),
        migrations.CreateModel(
            name='rangoDimensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bmin', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='B mínimo')),
                ('Bmax', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='B máximo')),
                ('each', models.DecimalField(decimal_places=3, max_digits=10)),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1')),
            ],
        ),
        migrations.CreateModel(
            name='preciosUnitarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioExc', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precioConcZ', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precioConcP', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precioRelleno', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preciosolado', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precioAceroZapata', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precioAceroPedestal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1')),
            ],
        ),
        migrations.CreateModel(
            name='precioMaterialCimentacionProfunda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Madera', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Acero', models.DecimalField(decimal_places=3, max_digits=10)),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1')),
            ],
        ),
        migrations.CreateModel(
            name='geometriaCimentacionProfunda',
            fields=[
                ('idDado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('diametroI', models.DecimalField(decimal_places=3, max_digits=10)),
                ('diametrof', models.DecimalField(decimal_places=3, max_digits=10)),
                ('material', models.CharField(choices=[('Concreto', 'concreto'), ('Madera', 'madera'), ('Acero', 'acero')], max_length=32)),
                ('resistenciaConcreto', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Carga', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Ep', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Eb', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ModuloMaterial', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tipoElemento', models.CharField(choices=[('Pilotes', 'pilotes'), ('Barretes', 'barretes'), ('Caissons', 'caissons')], max_length=32)),
                ('transCarga', models.CharField(choices=[('Friccion', 'friccion'), ('Punta', 'punta'), ('Minimo', 'mínimo'), ('Maximo', 'máximo'), ('Promedio', 'promedio')], max_length=32)),
                ('B', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='B: 0.6')),
                ('R', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='H: 2')),
                ('peso', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=32)),
                ('prof', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Profundidad cimentacion')),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1')),
            ],
        ),
        migrations.CreateModel(
            name='eficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(choices=[('CL', 'Converse-Labarre'), ('GA', 'Group Action'), ('SK', 'Seiler Keeney 1944'), ('Min', 'Minimo'), ('Max', 'Maximo'), ('Med', 'Mediano'), ('Media', 'Promedio')], max_length=32)),
                ('sepx', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sepy', models.DecimalField(decimal_places=3, max_digits=10)),
                ('offsetX', models.DecimalField(decimal_places=3, max_digits=10)),
                ('offsetY', models.DecimalField(decimal_places=3, max_digits=10)),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1')),
            ],
        ),
        migrations.CreateModel(
            name='diferenciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joints', models.IntegerField(verbose_name='JOINTS')),
                ('vecinos', models.IntegerField()),
                ('distancias', models.DecimalField(decimal_places=3, max_digits=10)),
                ('criterioDiferencial', models.DecimalField(decimal_places=4, max_digits=10)),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1')),
            ],
        ),
        migrations.CreateModel(
            name='datosPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espesorZapata', models.DecimalField(decimal_places=3, max_digits=10)),
                ('espesorSolado', models.DecimalField(decimal_places=3, max_digits=10)),
                ('espesorPedestal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('condicion', models.CharField(choices=[('mayorBL', 'MayorBL'), ('menorBL', 'MayorBL')], max_length=32)),
                ('cuantiaAceroZapata', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cuantiaAceroPedestal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1')),
            ],
        ),
        migrations.CreateModel(
            name='datosConsProfunda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bdado', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Lado horizontal del dado')),
                ('Ldado', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Lado vertical del dado')),
                ('H', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='H (en centímetros)')),
                ('Amax', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Asentamiento Máximo')),
                ('CargaMax', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Carga Máxima')),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.home1')),
            ],
        ),
    ]
