# Generated by Django 4.0.4 on 2022-04-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosIniciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelFeatico', models.DecimalField(decimal_places=4, max_digits=10)),
                ('profundidadCimentacion', models.DecimalField(decimal_places=4, max_digits=10)),
                ('factorResistencia', models.DecimalField(decimal_places=4, max_digits=10)),
                ('modelo', models.CharField(choices=[('hansen', 'Hansen'), ('vesic', 'Vesic')], max_length=32)),
                ('asentamimientoMaximo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('OCR', models.CharField(choices=[('si', 'SI'), ('no', 'NO')], max_length=32)),
                ('h', models.DecimalField(decimal_places=3, max_digits=10)),
                ('aumentoB', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cifrasDecimales', models.IntegerField()),
                ('salto', models.DecimalField(decimal_places=3, max_digits=10)),
                ('personalizado', models.CharField(choices=[('si', 'SI'), ('no', 'NO')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='dimensionesPersonalizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpersonalizado', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lpersonalizado', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('joints', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fuerza1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fuerza2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fuerza3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('momento1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('momento2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('momento3', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
